
# ========================== EASY QUESTIONS ==========================
easy_questions = [
    ("Which of the following is a programming language?", ["HTML", "Python", "CSS", "XML"], "Python"),
    ("The CPU is considered the what of a PC?", ["Brain", "Memory", "Storage", "Power"], "Brain"),
    ("Which device stores data permanently?", ["RAM", "ROM", "SSD", "Cache"], "SSD"),
    ("Which component handles computer graphics?", ["GPU", "CPU", "RAM", "HDD"], "GPU"),
    ("CSS is used for what purpose?", ["Structure", "Style", "Logic", "Database"], "Style"),
    ("What does RAM stand for?", ["Random Access Memory", "Read All Memory", "Rapid Access Memory", "Run And Memory"], "Random Access Memory"),
    ("The power supply provides what to the computer?", ["Compute", "Store", "Electricity", "Cooling"], "Electricity"),
    ("Which of the following is an input device?", ["Keyboard", "Monitor", "Speaker", "Printer"], "Keyboard"),
    ("Which of the following is an output device?", ["Mouse", "Monitor", "Printer", "Keyboard"], "Monitor"),
    ("What is the shortcut to copy?", ["Ctrl+C", "Ctrl+V", "Ctrl+X", "Ctrl+Z"], "Ctrl+C"),
    ("HTML is mainly used for what?", ["Styling", "Structuring", "Logic", "Database"], "Structuring"),
    ("Which of the following is volatile memory?", ["RAM", "SSD", "ROM", "HDD"], "RAM"),
    ("The BIOS is stored in which type of memory?", ["RAM", "ROM", "SSD", "Cache"], "ROM"),
    ("Python is considered what type of programming language?", ["Low-level", "High-level", "Assembly", "Machine code"], "High-level"),
    ("What does GPU stand for?", ["Graphical Processing Unit", "General Processing Unit", "Graphics Peripheral Unit", "General Programming Unit"], "Graphical Processing Unit"),
    ("What does SSD stand for?", ["Solid State Drive", "Super Storage Device", "Storage Solid Disk", "System State Disk"], "Solid State Drive"),
    ("Which operating system is developed by Microsoft?", ["Linux", "Windows", "macOS", "Android"], "Windows"),
    ("Which of the following is an open-source operating system?", ["Windows", "Linux", "macOS", "iOS"], "Linux"),
    ("Which type of storage is faster?", ["HDD", "SSD", "ROM", "RAM"], "SSD"),
    ("A monitor measures what?", ["Voltage", "Time", "Output", "Temperature"], "Output"),
    ("A speaker outputs which type of signal?", ["Audio", "Video", "Data", "Signal"], "Audio"),
    ("The mouse is classified as what type of device?", ["Input", "Output", "Storage", "Processor"], "Input"),
    ("A printer is classified as what type of device?", ["Input", "Output", "Processor", "Memory"], "Output"),
    ("What is the shortcut to paste?", ["Ctrl+P", "Ctrl+V", "Ctrl+C", "Ctrl+X"], "Ctrl+V"),
    ("What is the shortcut to cut?", ["Ctrl+X", "Ctrl+C", "Ctrl+V", "Ctrl+Z"], "Ctrl+X"),
    ("What is the shortcut to undo?", ["Ctrl+Z", "Ctrl+Y", "Ctrl+U", "Ctrl+X"], "Ctrl+Z"),
    ("Which HTML tag is used for paragraphs?", ["<p>", "<h1>", "<div>", "<span>"], "<p>"),
    ("Which CSS property is used to change font color?", ["color", "background", "size", "border"], "color"),
    ("RAM is what type of memory?", ["Volatile", "Non-Volatile", "Permanent", "SSD"], "Volatile"),
    ("ROM is what type of memory?", ["Volatile", "Non-Volatile", "Temporary", "Cache"], "Non-Volatile"),
    ("Who created Python?", ["Guido", "Linus", "Bill", "Mark"], "Guido"),
    ("How many digits does the binary system use?", ["2", "8", "10", "16"], "2"),
    ("One byte equals how many bits?", ["8 bits", "16 bits", "32 bits", "4 bits"], "8 bits"),
    ("A USB port works as what type of port?", ["Input", "Output", "Both", "Storage"], "Both"),
    ("Which of the following is a type of monitor?", ["LED", "CPU", "GPU", "RAM"], "LED"),
    ("A keyboard is what type of device?", ["Input", "Output", "Storage", "GPU"], "Input"),
    ("A mouse is what type of device?", ["Input", "Output", "Storage", "CPU"], "Input"),
    ("What does a router do?", ["Connects networks", "Stores data", "Processes code", "Prints"], "Connects networks"),
    ("What does a firewall block?", ["Hackers", "Files", "Programs", "Memory"], "Hackers"),
    ("Which of the following is an email client?", ["Outlook", "Chrome", "Linux", "Python"], "Outlook"),
    ("Which of the following is a search engine?", ["Google", "Python", "Linux", "Excel"], "Google"),
    ("Which of the following is a web browser?", ["Chrome", "Python", "Linux", "Excel"], "Chrome"),
    ("Which of the following is a phone operating system?", ["Android", "Windows", "Linux", "macOS"], "Android"),
    ("Which of the following is an app store?", ["Play Store", "GitHub", "Docker", "Visual Studio"], "Play Store"),
    ("Wi-Fi is what type of technology?", ["Wireless", "Wired", "Bluetooth", "USB"], "Wireless"),
    ("What does LAN stand for?", ["Local Area Network", "Long Area Network", "Large Area Network", "Light Area Network"], "Local Area Network"),
    ("What does an IP address represent?", ["Internet Protocol", "Internal Protocol", "Input Protocol", "Interface Protocol"], "Internet Protocol"),
    ("What is the purpose of HTTPS?", ["Secure", "Fast", "Cheap", "Public"], "Secure"),
    ("What is the purpose of HTTP?", ["Web", "Database", "Email", "Game"], "Web"),
    ("Which of the following is a type of server?", ["Web", "Graphics", "Audio", "Video"], "Web"),
    ("Which of the following is a type of client?", ["Web", "Storage", "GPU", "CPU"], "Web"),
    ("Which of the following is a type of database?", ["SQL", "HTML", "CSS", "JS"], "SQL"),
    ("Which app is used for spreadsheets?", ["Excel", "Word", "PowerPoint", "Access"], "Excel"),
    ("Which app is used for presentations?", ["PowerPoint", "Excel", "Word", "Access"], "PowerPoint"),
    ("Which app is used as a word processor?", ["Word", "Excel", "PowerPoint", "Access"], "Word"),
    ("Which of the following is a cloud storage service?", ["Google Drive", "Linux", "Python", "Windows"], "Google Drive")
]


# ========================== MEDIUM QUESTIONS ==========================
medium_questions = [
    ("Which language is commonly used for AI development?", ["C", "Python", "HTML", "PHP"], "Python"),
    ("Android apps are primarily developed using which language?", ["Python", "Java", "HTML", "CSS"], "Java"),
    ("Which of the following is a backend web language?", ["CSS", "JS", "Python", "XML"], "Python"),
    ("Which language is used to write database queries?", ["SQL", "Python", "HTML", "C++"], "SQL"),
    ("Which of these is an object-oriented language?", ["C", "Python", "HTML", "CSS"], "Python"),
    ("Which tool is used for version control?", ["Git", "Python", "Linux", "Java"], "Git"),
    ("Which language runs directly in the browser?", ["Python", "JS", "C++", "Java"], "JS"),
    ("Which of the following is NOT a backend language?", ["Python", "Ruby", "JS", "CSS"], "CSS"),
    ("SMTP is a protocol used for what?", ["HTTP", "FTP", "SMTP", "TCP"], "SMTP"),
    ("Which of the following is a Python web framework?", ["Django", "React", "Angular", "Vue"], "Django"),
    ("Which library is used for data analysis in Python?", ["Pandas", "NumPy", "Matplotlib", "React"], "Pandas"),
    ("Which language is used for iOS app development?", ["Java", "Swift", "C#", "PHP"], "Swift"),
    ("Which loop is used when the number of iterations is known?", ["for", "while", "do-while", "repeat"], "for"),
    ("Which loop is used when the number of iterations is unknown?", ["for", "while", "repeat", "switch"], "while"),
    ("Which language is strongly typed?", ["Python", "Java", "JS", "HTML"], "Java"),
    ("Which keyword is used to define a function in Python?", ["def", "func", "function", "define"], "def"),
    ("Which of the following is NOT a Python data type?", ["int", "str", "float", "bytecode"], "bytecode"),
    ("What error occurs when dividing a number by zero?", ["ValueError", "ZeroDivisionError", "TypeError", "IndexError"], "ZeroDivisionError"),
    ("Which HTML tag is used for headings?", ["<h1>", "<p>", "<div>", "<span>"], "<h1>"),
    ("Which CSS property sets the text color?", ["font-size", "color", "background", "border"], "color"),
    ("Which of the following is a Python IDE?", ["PyCharm", "Visual Studio", "Excel", "Word"], "PyCharm"),
    ("Which of the following is a JavaScript framework?", ["React", "Django", "Flask", "Ruby"], "React"),
    ("Which Python library is used for asynchronous programming?", ["asyncio", "threading", "multiprocessing", "os"], "asyncio"),
    ("Which module is used for threading in Python?", ["threading", "asyncio", "multiprocessing", "os"], "threading"),
    ("What does HTTP status code 404 mean?", ["Not Found", "OK", "Server Error", "Redirect"], "Not Found"),
    ("What does HTTP status code 200 mean?", ["OK", "Not Found", "Server Error", "Redirect"], "OK"),
    ("Which CSS model is used for layouts?", ["Flexbox", "Python", "SQL", "JS"], "Flexbox"),
    ("Which of the following is a JavaScript variable type?", ["let", "int", "float", "double"], "let"),
    ("Which keyword is used to stop a loop in Python?", ["break", "continue", "pass", "all"], "break"),
    ("Which of the following is a type of SQL join?", ["INNER", "LEFT", "RIGHT", "FULL"], "INNER"),
    ("Which of the following is a NoSQL database?", ["MongoDB", "MySQL", "SQLite", "PostgreSQL"], "MongoDB"),
    ("What is the Python package manager called?", ["pip", "npm", "apt", "gem"], "pip"),
    ("What is the JavaScript package manager called?", ["npm", "pip", "apt", "gem"], "npm"),
    ("Which of the following is a REST API method?", ["GET", "POST", "PUT", "DELETE"], "GET"),
    ("Which keyword defines a function in JavaScript?", ["function", "def", "func", "lambda"], "function"),
    ("Which keyword defines an anonymous function in Python?", ["lambda", "def", "func", "function"], "lambda"),
    ("Which keyword is used to create a class in Python?", ["class", "object", "def", "func"], "class"),
    ("Which CSS feature is used for responsive design?", ["media query", "flex", "grid", "script"], "media query"),
    ("Which of the following is a Python data type?", ["list", "div", "span", "body"], "list"),
    ("Which of the following is a JavaScript data type?", ["array", "list", "dict", "tuple"], "array"),
    ("Which loop is used in Python?", ["for", "foreach", "loop", "repeat"], "for"),
    ("Which loop is commonly used in JavaScript?", ["for", "foreach", "while", "do"], "for"),
    ("Which of the following is a Python error type?", ["IndexError", "FileNotFound", "SyntaxError", "RuntimeError"], "SyntaxError"),
    ("Which of the following is a JavaScript error type?", ["ReferenceError", "TypeError", "SyntaxError", "RangeError"], "ReferenceError"),
    ("Which keyword imports modules in Python?", ["import", "include", "require", "use"], "import"),
    ("Which keyword imports modules in JavaScript?", ["import", "include", "require", "use"], "import"),
    ("Which method adds an element to a Python list?", ["append", "add", "insert", "push"], "append"),
    ("Which method removes an element from a Python list?", ["remove", "delete", "pop", "discard"], "remove"),
    ("Which of the following represents a dictionary key in Python?", ["key", "index", "value", "attr"], "key"),
    ("Which of the following represents a dictionary value in Python?", ["value", "key", "index", "attr"], "value"),
    ("Which method converts a string to uppercase in Python?", ["upper", "append", "insert", "pop"], "upper"),
    ("Which of the following is a numeric type in Python?", ["int", "str", "list", "dict"], "int"),
    ("Which of the following is a boolean type in Python?", ["bool", "int", "str", "float"], "bool"),
    ("Which method adds an item to a Python set?", ["add", "append", "push", "insert"], "add"),
    ("Which function opens a file in Python?", ["open", "read", "write", "close"], "open"),
    ("Which function closes a file in Python?", ["close", "open", "read", "write"], "close"),
    ("Which structure handles exceptions in Python?", ["try-except", "if-else", "for", "while"], "try-except"),
    ("A Python package is also known as what?", ["library", "module", "script", "object"], "module"),
    ("Which tool creates a virtual environment in Python?", ["venv", "npm", "pip", "apt"], "venv")
]


# ========================== HARD QUESTIONS ==========================
hard_questions = [
    ("Which of the following is a system programming language?", ["Python", "C++", "HTML", "CSS"], "C++"),
    ("Which of the following is a compiled language?", ["Python", "JS", "C++", "HTML"], "C++"),
    ("Which of the following is an interpreted language?", ["Python", "C++", "Java", "C"], "Python"),
    ("Which of the following is a low-level language?", ["Assembly", "Python", "Java", "Ruby"], "Assembly"),
    ("Which of the following is NOT a high-level language?", ["C", "Java", "Python", "Ruby"], "C"),
    ("Which library is used for parallel computing?", ["MPI", "HTML", "CSS", "JS"], "MPI"),
    ("Which data structure follows FIFO?", ["Stack", "Queue", "Array", "Tree"], "Queue"),
    ("Which data structure follows LIFO?", ["Stack", "Queue", "Array", "Tree"], "Stack"),
    ("Which of the following is a NoSQL database?", ["MongoDB", "MySQL", "SQLite", "PostgreSQL"], "MongoDB"),
    ("Which protocol represents secure HTTP?", ["HTTP", "HTTPS", "FTP", "SMTP"], "HTTPS"),
    ("Which operating system uses a monolithic kernel?", ["Linux", "Windows", "macOS", "Android"], "Linux"),
    ("Which operating system uses a microkernel?", ["Windows", "macOS", "Linux", "Unix"], "macOS"),
    ("Which Python module is used for threading?", ["threading", "multiprocessing", "asyncio", "os"], "threading"),
    ("Which Python module is used for asynchronous operations?", ["threading", "multiprocessing", "asyncio", "os"], "asyncio"),
    ("Which algorithm uses the divide-and-conquer approach?", ["Merge Sort", "Bubble Sort", "Linear Search", "DFS"], "Merge Sort"),
    ("Which algorithm is used to find the shortest path?", ["Dijkstra", "DFS", "BFS", "Bubble Sort"], "Dijkstra"),
    ("Which of the following is a dynamically typed language?", ["Python", "Java", "C++", "C"], "Python"),
    ("Which of the following is a statically typed language?", ["Python", "Java", "JS", "Ruby"], "Java"),
    ("What does inheritance allow in OOP?", ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"], "Inheritance"),
    ("What does encapsulation hide in OOP?", ["Encapsulation", "Inheritance", "Polymorphism", "Abstraction"], "Encapsulation"),
    ("Which type of polymorphism occurs at runtime?", ["Compile-time", "Run-time", "Static", "Dynamic"], "Run-time"),
    ("Heap memory is used for what?", ["Dynamic", "Static", "Volatile", "Permanent"], "Dynamic"),
    ("Stack memory follows which principle?", ["LIFO", "FIFO", "Random", "Permanent"], "LIFO"),
    ("Which graph traversal methods are commonly used?", ["BFS", "DFS", "Both", "None"], "Both"),
    ("Which of the following is a sorting algorithm?", ["Quick Sort", "Linear Search", "DFS", "BFS"], "Quick Sort"),
    ("What does the base condition in recursion represent?", ["Condition", "Loop", "Function", "Variable"], "Condition"),
    ("What is the topmost node of a binary tree called?", ["Root", "Leaf", "Child", "Parent"], "Root"),
    ("Which property defines an AVL tree?", ["Balance", "Size", "Depth", "Weight"], "Balance"),
    ("What defines a Red-Black tree?", ["Color property", "Size", "Weight", "Depth"], "Color property"),
    ("When does a deadlock occur?", ["Concurrency", "Sequential", "Serial", "Parallel"], "Concurrency"),
    ("What is the purpose of a mutex?", ["Lock", "Unlock", "Create", "Delete"], "Lock"),
    ("Which types of semaphores exist?", ["Counting", "Binary", "Both", "None"], "Both"),
    ("Cache memory is described as what type of storage?", ["Fast storage", "Slow storage", "Permanent", "Volatile"], "Fast storage"),
    ("Virtual memory is composed of what?", ["Disk + RAM", "CPU", "GPU", "ROM"], "Disk + RAM"),
    ("How many bits are in an IPv4 address?", ["32", "64", "128", "16"], "32"),
    ("How many bits are in an IPv6 address?", ["128", "32", "64", "16"], "128"),
    ("DNS converts what?", ["Domain to IP", "IP to Domain", "Email", "Web"], "Domain to IP"),
    ("What is the function of a load balancer?", ["Distribute traffic", "Store data", "Compute", "Encrypt"], "Distribute traffic"),
    ("Which types of firewalls exist?", ["Packet filtering", "Proxy", "Both", "None"], "Both"),
    ("What is the purpose of TLS?", ["Encryption", "Speed", "Storage", "Compute"], "Encryption"),
    ("What is the relationship between SSL and TLS?", ["TLS updated SSL", "SSL updated TLS", "Same", "None"], "TLS updated SSL"),
    ("Which of the following is a cloud service model?", ["IaaS", "PaaS", "SaaS", "All"], "All"),
    ("Which tool is used for containerization?", ["Docker", "VM", "Python", "Linux"], "Docker"),
    ("Which tool is used for orchestration?", ["Kubernetes", "Docker", "Python", "Linux"], "Kubernetes"),
    ("Which tool is used for CI/CD automation?", ["Jenkins", "Docker", "Python", "Linux"], "Jenkins"),
    ("What are microservices?", ["Independent modules", "Monolith", "Library", "Framework"], "Independent modules"),
    ("What does serverless computing use?", ["Cloud functions", "VM", "Docker", "Kubernetes"], "Cloud functions"),
    ("What is the basic unit of a blockchain?", ["Block", "Node", "Chain", "Hash"], "Block"),
    ("What does a hash function do?", ["Maps data", "Stores data", "Transmits data", "Deletes data"], "Maps data"),
    ("What is a smart contract?", ["Code on blockchain", "App", "Database", "Server"], "Code on blockchain"),
    ("Which of the following are AI model types?", ["Supervised", "Unsupervised", "Reinforcement", "All"], "All"),
    ("Which of the following are layers in a neural network?", ["Hidden", "Input", "Output", "All"], "All"),
    ("What indicates overfitting?", ["High training accuracy", "Low training accuracy", "Random", "None"], "High training accuracy"),
    ("What indicates underfitting?", ["Low training accuracy", "High training accuracy", "Random", "None"], "Low training accuracy"),
    ("Gradient descent is used for what?", ["Optimization", "Sorting", "Searching", "Loop"], "Optimization"),
    ("Which of the following are activation functions?", ["Sigmoid", "ReLU", "Tanh", "All"], "All"),
    ("What does a loss function measure?", ["Error measure", "Accuracy", "Speed", "Memory"], "Error measure"),
    ("Which of the following are optimization algorithms?", ["SGD", "Adam", "RMSprop", "All"], "All"),
    ("What is method overloading?", ["Same name diff args", "Same name same args", "Diff name same args", "None"], "Same name diff args"),
    ("What is method overriding?", ["Subclass method", "Superclass method", "Any method", "None"], "Subclass method"),
    ("What does thread safety ensure?", ["Safe concurrent", "Unsafe concurrent", "None", "All"], "Safe concurrent"),
    ("What is a race condition?", ["Concurrent conflict", "Sequential conflict", "Loop", "None"], "Concurrent conflict"),
    ("How can deadlocks be prevented?", ["Lock order", "Random", "Loop", "None"], "Lock order")
]
